site_name: Postal3Script
site_author: WhackJob Interactive
site_description: Postal3Script
copyright: Written by Kizoky and Pseudonym_Tim <br>© WhackJob Interactive 2022<br>ㅤ
site_url: https://kizoky.github.io/postal3script
nav:
    - '-- Postal3Script (WIP) --':
        - 'What is Postal3Script?': 'index.md'
        - 'Structure (TBD)': 'TBD.md'
        - 'States (TBD)': 'TBD.md'
        - 'Patterns (TBD)': 'TBD.md'
        - 'Blocks (TBD)': 'TBD.md'
        - 'Events (TBD)': 'TBD.md'
    - '-- Attribute Checking --':
        - 'IfAttr, SetAttr, CheckAttr, ChangeAttr, RemoveAttr': 'attributes.md'
        - 'Embedded Attributes': 'embedattributes.md'
    - '-- Object Categories --':
        - 'Manner': 'manner.md'
        - 'Faction': 'faction.md'
        - 'ItemType': 'itemtype.md'
        - 'String (TBD)': 'TBD.md'
        - 'Timer (TBD)': 'TBD.md'
        - 'Object': 'object.md'
        - 'DistTo': 'distto.md'
        - 'AngleTo': 'angleto.md'
        - 'Visible': 'visible.md'
        - 'HasWeapon (TBD)': 'TBD.md'
        - 'RelationTo': 'relationto.md'
        - 'Relation': 'relation.md'
        - 'Name': 'name.md'
        - 'Ammo (TBD)': 'TBD.md'
        - 'Ignore (TBD)': 'TBD.md'
        - 'Karma (TBD)': 'TBD.md'
        - 'VoicePrefix': 'voiceprefix.md'
    - '-- State Functions --':
        - 'State, Pattern, ExecutePattern': 'func_state_pattern_executepattern.md'
        - 'Wait, WaitForEnd, Repeat': 'wait_waitforend_repeat.md'
        - 'StateMatrix': 'statematrix.md'
        - 'CallState, CallPattern': 'callstate_callpattern.md'
        - 'StoreActivityPattern, ExecuteActivityPattern, ClearActivityPattern': 'activitypattern_funcs.md'
    - '-- Misc Functions --':
        - 'Effect (TBD)': 'TBD.md'
        - 'FireEvent, FireEventEX, FireUser, FireInput, AreaEvent, EntFireUser, EntFireInput (TBD)': 'TBD.md'
        - 'Item, SpawnItem (TBD)': 'TBD.md'
        - 'AddFluid': 'addfluid.md'
        - 'Anchor, TargetAnchor (TBD)': 'TBD.md'
    - '-- NPC Functions --':
        - 'Say': 'say.md'
        - 'EmitSound': 'emitsound.md'
        - 'Gesture, ResetGesture, ResetSequence (TBD)': 'TBD.md'
        - 'Headblob': 'headblob.md'
        - 'NPC': 'NPC.md'
    - '-- NPC Behavior Functions --':
        - 'Aim, Face': 'aim_face.md'
        - 'Snatch, Unsnatch': 'snatch_unsnatch.md'
        - 'Senses, LookAt, LookOut': 'senses_lookat_lookout.md'
        - 'Crouch, Lean': 'crouch_lean.md'
        - 'Busy, Fear, Hate': 'busy_fear_hate.md'
        - 'Follow, PlayerFriendly': 'follow_playerfriendly.md'
        - 'CatDervish': 'catdervish.md'
        - 'StunOut': 'stunout.md'
        - 'EnableGibs': 'enablegibs.md'
        - 'EnterVehicle': 'entervehicle.md'
    - '-- Squad Functions --':
        - 'SetSquad, SetSquadRelation, RemoveSquadRelation': 'setsquad_relation.md'
        - 'RallySquad': 'rallysquad.md'
    - '-- Targeting Functions --':
        - 'TargetEntByName': 'targetentbyname.md'
        - 'SendTarget2Caller': 'sendtarget2caller.md'
        - 'CheckTarget, CheckLOS': 'checktarget_checklos.md'
        - 'ResetTarget, IgnoreTarget, SetTarget': 'reset_ignore_settarget.md'
        - 'TargetEnemy, TargetPlayer, TargetCaller, TargetItem, TargetVehicle, TargetHostage, TargetCrosshair': 'targetfunctions.md'
        - 'TargetToMem, TargetFromMem, CallerToMem, ClearMem': 'targetmemory.md'
        - 'AssistTarget, AssistEnemy, ArrestTarget, BusyTarget': 'assisttarget_enemy.md'
        - 'Relationship': 'relationship.md'
    - '-- Movement Functions --':
        - 'Move, MoveToLean, MoveToTarget, MoveToTargetLKP': 'movement_funcs.md'
        - 'FreeMovement, FreeMovementParams': 'freemovement.md'
        - 'TravelByPathTrack': 'travelbypathtrack.md'
        - 'SetHintGroup, SetAreaGroup, SetLeanGroup, AvoidProhibitedArea': 'sethint_area_leangroup_avoidarea.md'
        - 'Turn, TurnSpeed': 'turn_turnspeed.md'
        - 'SetActPack': 'setactpack.md'
    - '-- Attack Functions --':
        - 'Hit': 'hit.md'
        - 'Push': 'push.md'
        - 'Weapon, Reload, ThrowGrenade': 'weapon_reload_throwgrenade.md'
    - '-- Mission Functions --':
        - 'AttributeProgressBar': 'attributeprogressbar.md'
        - 'MissionLog, MissionSave, MissionBriefing': 'missionlog_save_briefing.md'
        - 'ShowMessage, ShowHint': 'showmessage_showhint.md'
        - 'EndMission': 'endmission.md'
        - 'PlayerKarma': 'playerkarma.md'
        - 'PlayVideo': 'playvideo.md'
        - 'OpenDialog': 'opendialog.md'
    - '-- Deleted Functions --':
        - 'Arm': 'arm.md'
        - 'HolsterWeapon': 'holsterweapon.md'
        - 'DesertSquad': 'desertsquad.md'
theme: readthedocs