theme: readthedocs
site_name: Postal3Script
site_author: WhackJob Interactive
site_description: Postal3Script
copyright: Written by Kizoky and Pseudonym_Tim <br>© WhackJob Interactive 2022<br>ㅤ
site_url: https://whackjobint.github.io/postal3script
markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
extra_css: [css/extra.css]
nav:
    - 'Postal3Script (WIP)':
        - 'Index': 'index.md'
        - 'What is Postal3Script?': 'whatispostal3script.md'
        - 'Structure (TBD)': 'TBD.md'
        - 'States (TBD)': 'TBD.md'
        - 'Patterns (TBD)': 'TBD.md'
        - 'Blocks (TBD)': 'TBD.md'
        - 'Events': 'events.md'
        - 'Hammer Functions (TBD)': 'TBD.md'
        - 'Development/WIP Files': 'wipp3sfiles.md'
        - 'Syntax Highlighter': 'syntaxhighlighter.md'
    - 'Attribute Checking':
        - 'IfAttr, SetAttr, CheckAttr, ChangeAttr, RemoveAttr': 'attribchecking/attributes.md'
        - 'Embedded Attributes': 'attribchecking/embedattributes.md'
    - 'Object Categories':
        - 'Manner': 'objects/manner.md'
        - 'Faction': 'objects/faction.md'
        - 'ItemType': 'objects/itemtype.md'
        - 'String': 'objects/string.md'
        - 'Timer': 'objects/timer.md'
        - 'Object': 'objects/object.md'
        - 'DistTo': 'objects/distto.md'
        - 'AngleTo': 'objects/angleto.md'
        - 'Visible': 'objects/visible.md'
        - 'HasWeapon': 'objects/hasweapon.md'
        - 'RelationTo': 'objects/relationto.md'
        - 'Relation': 'objects/relation.md'
        - 'Name': 'objects/name.md'
        - 'Ammo': 'objects/ammo.md'
        - 'Ignore': 'objects/ignore.md'
        - 'Karma': 'objects/karma.md'
        - 'VoicePrefix': 'objects/voiceprefix.md'
    - 'State Functions':
        - 'State, Pattern, ExecutePattern': 'statefuncs/func_state_pattern_executepattern.md'
        - 'Wait, WaitForEnd, Repeat': 'statefuncs/wait_waitforend_repeat.md'
        - 'StateMatrix': 'statefuncs/statematrix.md'
        - 'CallState, CallPattern, Call (WIP)': 'statefuncs/callstate_callpattern.md'
        - 'StoreActivityPattern, ExecuteActivityPattern, ClearActivityPattern': 'statefuncs/activitypattern_funcs.md'
        - 'SendState, SendPattern (TBD)': 'TBD.md'
    - 'Misc Functions':
        - 'Effect': 'miscfuncs/effect.md'
        - 'FireEvent, FireEventEX, FireUser, OnUser, FireInput, AreaEvent, EntFireUser, EntFireInput (WIP)': 'miscfuncs/fire_event_and_user_funcs.md'
        - 'Item, SpawnItem': 'miscfuncs/item_spawnitem.md'
        - 'AddFluid': 'miscfuncs/addfluid.md'
        - 'Anchor, TargetAnchor (TBD)': 'TBD.md'
    - 'NPC Functions':
        - 'Say': 'npcfuncs/say.md'
        - 'EmitSound': 'npcfuncs/emitsound.md'
        - 'Gesture, ResetGesture, ResetSequence': 'npcfuncs/gesture_resetgesture_resetsequence.md'
        - 'Headblob': 'npcfuncs/headblob.md'
        - 'NPC': 'npcfuncs/NPC.md'
    - 'NPC Behavior Functions':
        - 'Aim, Face': 'npcbehaviorfuncs/aim_face.md'
        - 'Snatch, Unsnatch': 'npcbehaviorfuncs/snatch_unsnatch.md'
        - 'Senses, LookAt, LookOut': 'npcbehaviorfuncs/senses_lookat_lookout.md'
        - 'Crouch, Lean': 'npcbehaviorfuncs/crouch_lean.md'
        - 'Busy, Hate': 'npcbehaviorfuncs/busy_hate.md'
        - 'Follow, PlayerFriendly': 'npcbehaviorfuncs/follow_playerfriendly.md'
        - 'CatDervish': 'npcbehaviorfuncs/catdervish.md'
        - 'StunOut': 'npcbehaviorfuncs/stunout.md'
        - 'EnableGibs': 'npcbehaviorfuncs/enablegibs.md'
        - 'EnterVehicle': 'npcbehaviorfuncs/entervehicle.md'
    - 'Squad Functions':
        - 'SetSquad, SetSquadRelation, RemoveSquadRelation': 'squadfuncs/setsquad_relation.md'
        - 'RallySquad': 'squadfuncs/rallysquad.md'
    - 'Targeting Functions':
        - 'TargetEntByName': 'targetingfuncs/targetentbyname.md'
        - 'SendTarget2Caller, SendCaller': 'targetingfuncs/sendtarget2caller_sendcaller.md'
        - 'CheckTarget, CheckLOS': 'targetingfuncs/checktarget_checklos.md'
        - 'ResetTarget, IgnoreTarget, SetTarget': 'targetingfuncs/reset_ignore_settarget.md'
        - 'TargetEnemy, TargetPlayer, TargetCaller, TargetItem, TargetVehicle, TargetHostage, TargetCrosshair': 'targetingfuncs/targetfunctions.md'
        - 'TargetToMem, TargetFromMem, CallerToMem, ClearMem': 'targetingfuncs/targetmemory.md'
        - 'AssistTarget, AssistEnemy, ArrestTarget, BusyTarget': 'targetingfuncs/assisttarget_enemy.md'
        - 'Relationship': 'targetingfuncs/relationship.md'
    - 'Movement Functions':
        - 'Move, MoveToLean, MoveToTarget, MoveToTargetLKP': 'movementfuncs/movement_funcs.md'
        - 'FreeMovement, FreeMovementParams': 'movementfuncs/freemovement.md'
        - 'TravelByPathTrack': 'movementfuncs/travelbypathtrack.md'
        - 'SetHintGroup, SetAreaGroup, SetLeanGroup, AvoidProhibitedArea': 'movementfuncs/sethint_area_leangroup_avoidarea.md'
        - 'Turn, TurnSpeed': 'movementfuncs/turn_turnspeed.md'
        - 'SetActPack': 'movementfuncs/setactpack.md'
    - 'Attack Functions':
        - 'Hit': 'attackfuncs/hit.md'
        - 'Push': 'attackfuncs/push.md'
        - 'Weapon, Reload, ThrowGrenade': 'attackfuncs/weapon_reload_throwgrenade.md'
    - 'Mission Functions':
        - 'AttributeProgressBar': 'missionfuncs/attributeprogressbar.md'
        - 'MissionLog, MissionSave, MissionBriefing': 'missionfuncs/missionlog_save_briefing.md'
        - 'ShowMessage, ShowHint': 'missionfuncs/showmessage_showhint.md'
        - 'EndMission': 'missionfuncs/endmission.md'
        - 'PlayerKarma': 'missionfuncs/playerkarma.md'
        - 'PlayVideo': 'missionfuncs/playvideo.md'
        - 'OpenDialog': 'missionfuncs/opendialog.md'
    - 'Deleted Functions':
        - 'ActBusy': 'deletedfuncs/actbusy.md'
        - 'Arm': 'deletedfuncs/arm.md'
        - 'HolsterWeapon': 'deletedfuncs/holsterweapon.md'
        - 'DesertSquad': 'deletedfuncs/desertsquad.md'
        - 'Fear': 'deletedfuncs/fear.md'
    - 'Mission Script Files (Pre-Path)':
        - 'PDB (Paradise Bridge)': 'missions/pdb.md'
        - 'PW (Porn World)': 'missions/pw.md'
        - 'DCR (Diseased Cat Roundup)': 'missions/dcr.md'
        - 'JWB (Jen Walcotts Bodyguard)': 'missions/jwb.md'
        - 'CM (Cash Mart Robbery)': 'missions/cm.md'
    - 'Mission Script Files (Good Path)':
        - 'PA (Police Academy) TBD': 'TBD.md'
        - 'PM1 (Patrol Mission 1) TBD': 'TBD.md'
        - 'SUB (Save Uwe Bolls Career) TBD': 'TBD.md'
        - 'AS (Arcade Shootout) TBD': 'TBD.md'
        - 'HI (Homeland Insecurity) TBD': 'TBD.md'
        - 'MLG (Police Monkey Test Lab Assault) TBD': 'TBD.md'
        - 'PM2 (Patrol Mission 2) TBD': 'TBD.md'
        - 'ZHQA (Eco Zealot HQ Assault) TBD': 'TBD.md'
        - 'GRG (Police Gay Rodeo) TBD': 'TBD.md'
        - 'MC (The Motorcade) TBD': 'TBD.md'
        - 'DLG (Police Daveland) TBD': 'TBD.md'
        - 'AA (Apocalypse Again) TBD': 'TBD.md'
    - 'Mission Script Files (Insane Path)':
        - 'MTZ (Meet the Zealots) TBD': 'TBD.md'
        - 'CW (The Champ Whisperer) TBD': 'TBD.md'
        - 'SRM (Segway Repo Man) TBD': 'TBD.md'
        - 'SBE (Slave Boy Escort) TBD': 'TBD.md'
        - 'MLI (Monkey Test Lab Assault) TBD': 'TBD.md'
        - 'KMTD (Krotchy Meal Toy Delivery) TBD': 'TBD.md'
        - 'MVC (Mexican Viagra Courier) TBD': 'TBD.md'
        - 'PWAC (Prisoner Without A Clue) TBD': 'TBD.md'
        - 'BDK (Battle Damage Krotchy) TBD': 'TBD.md'
        - 'GRI (Gay Rodeo) TBD': 'TBD.md'
        - 'CRM (Champ Rescue) TBD': 'TBD.md'
        - 'DLI (Daveland) TBD': 'TBD.md'