site_name: Postal3Script
site_author: Whackjob Interactive
site_description: Postal3Script
copyright: Written by Kizoky and Pseudonym_Tim <br>© Whackjob Interactive 2022<br>ㅤ
site_url: https://kizoky.github.io/postal3script
nav:
    - 'Postal3Script':
        - 'What is Postal3Script?': 'index.md'
        - 'Structure(tbd)': 'TBD.md'
        - 'States(tbd)': 'TBD.md'
        - 'Patterns(tbd)': 'TBD.md'
        - 'Blocks(tbd)': 'TBD.md'
        - 'Events(tbd)': 'TBD.md'
    - 'Attribute Checking':
        - 'IfAttr, SetAttr, CheckAttr, ChangeAttr, RemoveAttr': 'attributes.md'
        - 'Embedded Attributes': 'embedattributes.md'
    - 'Object Categories':
        - 'Manner': 'manner.md'
        - 'Faction': 'faction.md'
        - 'ItemType(tbd)': 'TBD.md'
        - 'String(tbd)': 'TBD.md'
        - 'Timer(tbd)': 'TBD.md'
        - 'Object': 'object.md'
        - 'DistTo(tbd)': 'TBD.md'
        - 'AngleTo(tbd)': 'TBD.md'
        - 'Visible(tbd)': 'TBD.md'
        - 'HasWeapon(tbd)': 'TBD.md'
        - 'RelationTo(tbd)': 'TBD.md'
        - 'Relation(tbd)': 'TBD.md'
        - 'Name': 'name.md'
        - 'Ammo(tbd)': 'TBD.md'
        - 'Ignore(tbd)': 'TBD.md'
        - 'Karma(tbd)': 'TBD.md'
        - 'VoicePrefix(tbd)': 'TBD.md'
    - 'Functions (WIP)':
        - 'Effect': 'TBD.md'
        - 'Say': 'TBD.md'
        - 'FireEvent, FireEventEX, FireUser, FireInput, AreaEvent, EntFireUser, EntFireInput': 'TBD.md'
        - 'State, Pattern, ExecutePattern': 'TBD.md'
        - 'SetSquad, SetSquadRelation, RemoveSquadRelation, RallySquad, DesertSquad': 'TBD.md'
        - 'SetHintGroup, SetAreaGroup, SetLeanGroup, AvoidProhibitedArea': 'TBD.md'
        - 'TargetEnemy, TargetPlayer, TargetCaller, TargetItem, TargetAnchor, TargetVehicle, TargetHostage, TargetCrosshair, TargetEntByName, ResetTarget, IgnoreTarget, SetTarget': 'TBD.md'
        - 'TargetToMem, TargetFromMem, CallerToMem, ClearMem, SendTarget2Caller': 'TBD.md'
        - 'SetActPack': 'TBD.md'
        - 'FreeMovement, FreeMovementParams, MoveToLean, MoveToTarget, MoveToTargetLKP, MoveToNode': 'TBD.md'
        - 'Wait, WaitForEnd, Repeat': 'TBD.md'
        - 'Gesture, ResetGesture, ResetSequence': 'TBD.md'
        - 'Turn, TurnSpeed': 'TBD.md'
        - 'Aim, Senses, Snatch, Unsnatch, Crouch, Face, Lean, Follow, LookAt, HolsterWeapon, Anchor, Busy, Fear, Hate, CatDervish, PlayerFriendly, LookOut': 'TBD.md'
        - 'Headblob': 'TBD.md'
        - 'StateMatrix': 'TBD.md'
        - 'CallState, CallPattern': 'TBD.md'
        - 'EmitSound': 'TBD.md'
        - 'Item, SpawnItem': 'TBD.md'
        - 'Weapon, Reload, ThrowGrenade': 'TBD.md'
        - 'Relationship': 'TBD.md'
        - 'EnterVehicle': 'TBD.md'
        - 'Hit': 'TBD.md'
        - 'Arm': 'TBD.md'
        - 'AssistTarget, AssistEnemy, ArrestTarget, BusyTarget, CheckTarget, CheckLOS': 'TBD.md'
        - 'NPC': 'TBD.md'
        - 'Push': 'TBD.md'
        - 'StunOut': 'TBD.md'
        - 'EnableGibs': 'TBD.md'
        - 'StoreActivityPattern, ExecuteActivityPattern, ClearActivityPattern': 'TBD.md'
        - 'TravelByPathTrack': 'TBD.md'
        - 'AddFluid': 'TBD.md'
    - 'Mission Functions (WIP)':
        - 'AttributeProgressBar': 'TBD.md'
        - 'MissionLog, MissionSave, MissionBriefing': 'TBD.md'
        - 'ShowMessage, ShowHint': 'TBD.md'
        - 'EndMission': 'TBD.md'
        - 'PlayerKarma': 'TBD.md'
        - 'PlayVideo': 'TBD.md'
        - 'OpenDialog (YesNo)': 'TBD.md'
theme: readthedocs