site_name: Postal3Script
site_author: WhackJob Interactive
site_description: Postal3Script
copyright: Written by Kizoky and Pseudonym_Tim <br>© WhackJob Interactive 2022<br>ㅤ
site_url: https://kizoky.github.io/postal3script
nav:
    - '-- Postal3Script (WIP) --':
        - 'What is Postal3Script?': 'index.md'
        - 'Structure (TBD)': 'TBD.md'
        - 'States (TBD)': 'TBD.md'
        - 'Patterns (TBD)': 'TBD.md'
        - 'Blocks (TBD)': 'TBD.md'
        - 'Events (TBD)': 'TBD.md'
    - '-- Attribute Checking --':
        - 'IfAttr, SetAttr, CheckAttr, ChangeAttr, RemoveAttr': 'attributes.md'
        - 'Embedded Attributes': 'embedattributes.md'
    - '-- Object Categories (WIP) --':
        - 'Manner': 'manner.md'
        - 'Faction': 'faction.md'
        - 'ItemType (TBD)': 'TBD.md'
        - 'String (TBD)': 'TBD.md'
        - 'Timer (TBD)': 'TBD.md'
        - 'Object': 'object.md'
        - 'DistTo': 'distto.md'
        - 'AngleTo (TBD)': 'TBD.md'
        - 'Visible': 'visible.md'
        - 'HasWeapon (TBD)': 'TBD.md'
        - 'RelationTo (TBD)': 'TBD.md'
        - 'Relation (TBD)': 'TBD.md'
        - 'Name': 'name.md'
        - 'Ammo (TBD)': 'TBD.md'
        - 'Ignore (TBD)': 'TBD.md'
        - 'Karma (TBD)': 'TBD.md'
        - 'VoicePrefix': 'voiceprefix.md'
    - '-- Functions (WIP) --':
        - 'Effect (TBD)': 'TBD.md'
        - 'Say': 'say.md'
        - 'FireEvent, FireEventEX, FireUser, FireInput, AreaEvent, EntFireUser, EntFireInput (TBD)': 'TBD.md'
        - 'SetSquad, SetSquadRelation, RemoveSquadRelation, RallySquad, DesertSquad (TBD)': 'TBD.md'
        - 'TargetEnemy, TargetPlayer, TargetCaller, TargetItem, TargetAnchor, TargetVehicle, TargetHostage, TargetCrosshair, TargetEntByName, ResetTarget, IgnoreTarget, SetTarget (TBD)': 'TBD.md'
        - 'TargetToMem, TargetFromMem, CallerToMem, ClearMem, SendTarget2Caller (TBD)': 'TBD.md'
        - 'Gesture, ResetGesture, ResetSequence (TBD)': 'TBD.md'
        - 'Aim, Senses, Snatch, Unsnatch, Crouch, Face, Lean, Follow, LookAt, HolsterWeapon, Anchor, Busy, Fear, Hate, CatDervish, PlayerFriendly, LookOut (TBD)': 'TBD.md'
        - 'Headblob (TBD)': 'TBD.md'
        - 'EmitSound (TBD)': 'TBD.md'
        - 'Item, SpawnItem (TBD)': 'TBD.md'
        - 'Relationship (TBD)': 'TBD.md'
        - 'EnterVehicle (TBD)': 'TBD.md'
        - 'AssistTarget, AssistEnemy, ArrestTarget, BusyTarget, CheckTarget, CheckLOS': 'assisttarget_enemy.md'
        - 'NPC': 'NPC.md'
        - 'StunOut': 'stunout.md'
        - 'EnableGibs': 'enablegibs.md'
        - 'AddFluid': 'addfluid.md'
    - '-- State Functions --':
        - 'State, Pattern, ExecutePattern': 'func_state_pattern_executepattern.md'
        - 'Wait, WaitForEnd, Repeat': 'wait_waitforend_repeat.md'
        - 'StateMatrix': 'statematrix.md'
        - 'CallState, CallPattern': 'callstate_callpattern.md'
        - 'StoreActivityPattern, ExecuteActivityPattern, ClearActivityPattern': 'activitypattern_funcs.md'
    - '-- Movement Functions --':
        - 'Move, MoveToLean, MoveToTarget, MoveToTargetLKP, MoveToNode (TBD)': 'TBD.md'
        - 'FreeMovement, FreeMovementParams (TBD)': 'TBD.md'
        - 'TravelByPathTrack': 'travelbypathtrack.md'
        - 'SetHintGroup, SetAreaGroup, SetLeanGroup, AvoidProhibitedArea (TBD)': 'TBD.md'
        - 'Turn, TurnSpeed': 'turn_turnspeed.md'
        - 'SetActPack (TBD)': 'TBD.md'
    - '-- Attack Functions --':
        - 'Hit': 'hit.md'
        - 'Push': 'push.md'
        - 'Weapon, Reload, ThrowGrenade': 'weapon_reload_throwgrenade.md'
    - '-- Mission Functions --':
        - 'AttributeProgressBar': 'attributeprogressbar.md'
        - 'MissionLog, MissionSave, MissionBriefing': 'missionlog_save_briefing.md'
        - 'ShowMessage, ShowHint': 'showmessage_showhint.md'
        - 'EndMission': 'endmission.md'
        - 'PlayerKarma': 'playerkarma.md'
        - 'PlayVideo': 'playvideo.md'
        - 'OpenDialog': 'opendialog.md'
    - '-- Deleted Functions --':
        - 'Arm': 'arm.md'
theme: readthedocs